"""
FIRST PICK = BLUE; SECOND PICK = RED
"""

"""
DRAFT:
"""
"""
--------------------
>BLUE 1ST PICK
>RED 1ST PICK
>RED 2ND PICK
>BLUE 2ND PICK
>BLUE 3RD PICK
>RED 3RD PICK
>RED 4TH PICK
>BLUE 4TH PICK
>BLUE 5TH PICK
>RED 5TH PICK
>SIMULTANEOUS BANS
>SELECT IMPRINT CONCENTRATIONS AND RELEASES
>SELECT UNIT POSITIONING
>DRAFT ENDS
"""

"""
COMBAT:
"""
"""
-------------------
START OF BATTLE
>APPLY START OF COMBAT EFFECTS (GUIDING LIGHT, HWAYOUNG SHIELD, FCC SHIELD, ETC.)
>CALCULATE FIRST CHARACTER TO MOVE

PRE ATTACK
>POISON/BURN/BLEED/BOMB DAMAGE/EFFECTS APPLY

CHOOSE ATTACK
>CHECK SILENCE
>CHECK COOLDOWNS
>SELECT ABILITY
>SELECT TARGET(S)
>USE ABILITY
>SET USED ABILITY COOLDOWN
>TRIGGER OTHER CHARACTER'S EFFECTS

POST ATTACK
>COOLDOWNS -= 1
>DEBUFF DURATIONS -= 1

CALCULATE NEXT UNIT TO TAKE THE TURN
"""